### PR TITLE
[FIX] runbot_send_email: Colapse into a same email thread

### PR DESCRIPTION
**Pull request by luiseevaquer**
https://github.com/Vauxoo/runbot-addons/issues/61

**Example of same email colapsed:**

**\* For PR change:**

colapse_03

colapse_04

**\* For branch change:**

colapse_01

colapse_02

### CODE REVIEW

**Comment by zaoral** [comment]
Hi @lescobarvx
Thanks for the contribution

IMHO I have some reviews I want to share:
- I think that for PRs the SHA number should not be include in the email title.
  In your test, I suspect that you run again the same commit `1e669b60`. But in a PR case, the SHA number will be different with every commit. So the result will be not colapse thread: will be one thread per commit and we would like to accomplish one thread by PR.
-  The first plain text of in the body of the message could have both the testing result and the SHA number, no matter if this information repeat in the message. a plain text with this two values could be helpfull when reading the message from the inbox. As you can see I highlight your image 

image

the first plain text line of the email is shown along with the title message in your inbox. So if you add the testing result with the SHA number at the beginning of the message the result could be something like this

> **Administrator (2)       [runbot] vauxoo/instance # 450** - Broken 1e669b60

Best Regards

**Comment by luiseevaquer** [comment]
@zaoral  
could you check images examples again?
just need to change the header of the message body

**Comment by luiseevaquer** [comment]
@nhomar 
Can you indicate me which is the module that overrides the header of the message body, please?

**Comment by zaoral** [comment]
Hi @lescobarvx 
I did not see the two image before.
Ok, thanks for the change.

**Comment by luiseevaquer** [comment]
@zaoral 
sorry, I updated the images after you did the comment

**Comment by luiseevaquer** [comment]
@zaoral 
example of the modification of header of the message body:

head_body

**Comment by zaoral** [comment]
LGTM @lescobarvx

**Comment by moylop260** [comment]
FYI changed applied in production server

**Comment by zaoral** [comment]
Excellent!
Thanks for the contribution guys @lescobarvx @moylop260

**Comment by luiseevaquer** [comment]
@zaoral You're welcome!

**Pull request merged**
